version: "3.9"

services:
  llama-cpp:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda13
    container_name: llama-cpp-qwen3.6-35b-a3b-q4-k-m-container
    restart: always
    ports:
      - "9722:8080"
    volumes:
      - models:/path/to/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # command: -m /path/to/models/Qwen3.6-35B-A3B-Q4_K_M.gguf --host 0.0.0.0 --port 8080 --n-gpu-layers 999 --n-predict -1 --ctx-size 16384 --context-shift --no-mmap --batch-size 512 --no-prompt-patience --no-checkpoints --threads 16
    # command: -m /path/to/models/Qwen3.6-27B-Q3_K_M.gguf --host 0.0.0.0 --port 8080 --n-gpu-layers 999 --n-predict -1 --ctx-size 16384 --context-shift --no-mmap --batch-size 512 --threads 8
    # command: -m /path/to/models/Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf --host 0.0.0.0 --port 8080 --ctx-size 262144 -ngl 99 --cache-type-k q8_0 --cache-type-v q8_0 --keep 512 --batch-size 512 --ubatch-size 256 --threads 8 --threads-batch 16 --parallel 1 --timeout 1800 --cache-reuse 256 --poll 50 --flash-attn auto --fit off --reasoning off --reasoning-budget 0 --jinja --repeat-penalty 1.1
    command: -m /path/to/models/Qwen3.6-35B-A3B-Q4_K_M.gguf --host 0.0.0.0 --port 8080 --ctx-size 262144 -ngl 99 --cache-type-k q8_0 --cache-type-v q8_0 --keep 512 --batch-size 512 --ubatch-size 256 --threads 8 --threads-batch 16 --parallel 1 --timeout 1800 --cache-reuse 256 --poll 50 --flash-attn auto --fit off --reasoning off --reasoning-budget 0 --jinja --repeat-penalty 1.1
    networks:
      - llama-cpp-network

volumes:
  models:
    driver: local
    driver_opts:
      type: none
      device: ${MODELS_PATH}
      o: bind
  pgadmin-data:

networks:
  llama-cpp-network:
    driver: bridge